import { Router } from 'express';
import { products, orders, shops, users } from '../store/memoryStore';
import { requireAuth, requireRole } from '../auth/middleware';
import { mongoDb } from '../db/mongodb';
import { createUser, findOrders, listShops, listStaff } from '../db/repositories';
import { hashPassword } from '../auth/password';
import { adminCatalog } from './adminCatalog';
import { approveSalesImport, rejectSalesImport } from './onboarding';
import type { PartnerApplicationType } from './onboarding';
import type { SalesImport, User } from '../models/domain';
import { ensurePartnerCredentialPools, getPartnerCredentialBase, listPartnerCredentialPool, claimPartnerCredential } from '../auth/shopCredentials';
import { partnerAdmin } from './partnerAdmin';

export const admin = Router();
admin.use(requireAuth, requireRole('admin', 'super_admin'));
admin.use('/catalog', adminCatalog);
admin.use('/partners', partnerAdmin);
const requireSuperAdmin = (req: any, res: any, next: any) => req.user?.role !== 'super_admin' ? res.status(403).json({ error: 'Super admin access required' }) : next();

admin.get('/dashboard', async (_req, res) => {
  try { if (mongoDb()) { const db = mongoDb()!; const [allOrders, allProducts, allShops, staff] = await Promise.all([findOrders(), db.collection<import('../models/domain').Product>('products').find({}).toArray(), listShops(), listStaff()]); const delivered = allOrders.filter(o => o.status === 'DELIVERED'); return res.json({ revenue: delivered.reduce((sum, order) => sum + order.total, 0), activeOrders: allOrders.filter(o => !['DELIVERED', 'CANCELLED'].includes(o.status)).length, products: allProducts.length, lowStock: allProducts.filter(p => p.stock <= p.minStock).length, shops: allShops.length, staff: staff.length }); } } catch (error) { console.error('Admin dashboard MongoDB read failed:', error); }
  const activeOrders = orders.filter(o => !['DELIVERED', 'CANCELLED'].includes(o.status)); const revenue = orders.filter(o => o.status === 'DELIVERED').reduce((s, o) => s + o.total, 0); return res.json({ revenue, activeOrders: activeOrders.length, products: products.length, lowStock: products.filter(p => p.stock <= p.minStock).length, shops: shops.filter(s => s.active).length, staff: users.filter(u => u.active && u.role !== 'customer').length });
});

admin.get('/super-dashboard', requireSuperAdmin, async (_req, res) => {
  try {
    const db = mongoDb();
    if (db) {
      const [allOrders, allShops, allProducts, allStaff, pendingApplications] = await Promise.all([db.collection<import('../models/domain').Order>('orders').find({}).toArray(), db.collection<import('../models/domain').Shop>('shops').find({}).toArray(), db.collection<import('../models/domain').Product>('products').find({}).toArray(), db.collection<User>('users').find({ role: { $in: ['shopkeeper', 'employee', 'store_manager'] }, active: true }).project({ passwordHash: 0 }).toArray(), db.collection('onboardingApplications').countDocuments({ status: 'PENDING_REVIEW' })]);
      const delivered = allOrders.filter(order => order.status === 'DELIVERED'); const revenue = delivered.reduce((sum, order) => sum + order.total, 0); const productMap = new Map(allProducts.map(product => [product.id, product])); let cost = 0;
      for (const order of delivered) for (const item of order.items) cost += (productMap.get(item.productId)?.costPrice ?? productMap.get(item.productId)?.sellingPrice ?? item.unitPrice) * item.quantity;
      const profit = revenue - cost; const shopsById = new Map(allShops.map(shop => [shop.id, shop])); const shopStats = new Map<string, { shopId:string; shopName:string; sales:number; orders:number; profit:number; units:number }>();
      for (const order of delivered) { const current = shopStats.get(order.shopId) ?? { shopId:order.shopId, shopName:shopsById.get(order.shopId)?.name ?? order.shopId, sales:0, orders:0, profit:0, units:0 }; current.sales += order.total; current.orders += 1; for (const item of order.items) { current.units += item.quantity; current.profit += (item.unitPrice - (productMap.get(item.productId)?.costPrice ?? productMap.get(item.productId)?.sellingPrice ?? item.unitPrice)) * item.quantity; } shopStats.set(order.shopId,current); }
      const topShops = [...shopStats.values()].map(item => ({ ...item, margin:item.sales ? (item.profit/item.sales)*100 : 0 })).sort((a,b)=>b.sales-a.sales); const byMonth = new Map<string,{month:string;sales:number;profit:number;orders:number}>();
      for (const order of delivered) { const month=order.createdAt.slice(0,7); const row=byMonth.get(month) ?? {month,sales:0,profit:0,orders:0}; row.sales += order.total; row.orders += 1; for (const item of order.items) row.profit += (item.unitPrice-(productMap.get(item.productId)?.costPrice ?? productMap.get(item.productId)?.sellingPrice ?? item.unitPrice))*item.quantity; byMonth.set(month,row); }
      return res.json({ totals:{sales:revenue,profit,margin:revenue?(profit/revenue)*100:0,orders:delivered.length,units:delivered.reduce((sum,o)=>sum+o.items.reduce((s,i)=>s+i.quantity,0),0),shops:allShops.filter(s=>s.active).length,staff:allStaff.length,pendingApplications}, topShops:topShops.slice(0,20), monthly:[...byMonth.values()].sort((a,b)=>a.month.localeCompare(b.month)).slice(-12) });
    }
  } catch (error) { console.error('Super dashboard MongoDB read failed:', error); }
  const delivered = orders.filter(order => order.status === 'DELIVERED'); const revenue = delivered.reduce((sum, order) => sum + order.total, 0); return res.json({ totals:{sales:revenue,profit:0,margin:0,orders:delivered.length,units:delivered.reduce((sum,o)=>sum+o.items.reduce((s,i)=>s+i.quantity,0),0),shops:shops.filter(s=>s.active).length,staff:users.filter(u=>u.active&&['shopkeeper','employee','store_manager'].includes(u.role)).length,pendingApplications:0}, topShops:[], monthly:[] });
});

admin.get('/super-dashboard/applications', requireSuperAdmin, async (req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for onboarding approvals'});const status=typeof req.query.status==='string'?req.query.status:'PENDING_REVIEW';const type=typeof req.query.type==='string'&&['shopkeeper','employee'].includes(req.query.type)?req.query.type as PartnerApplicationType:undefined;const applications=await db.collection('onboardingApplications').find({...(type?{type}:{}),...(status?{status}:{})}).sort({submittedAt:-1}).limit(200).toArray();return res.json(applications);});
admin.patch('/super-dashboard/applications/:referenceId',requireSuperAdmin,async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for onboarding approvals'});const status=req.body?.status;if(!['APPROVED','REJECTED'].includes(status))return res.status(400).json({error:'Status must be APPROVED or REJECTED'});const updated=await db.collection('onboardingApplications').findOneAndUpdate({referenceId:req.params.referenceId,status:'PENDING_REVIEW'},{$set:{status,reviewedBy:req.user!.id,reviewedAt:new Date().toISOString()}},{returnDocument:'after'});if(!updated)return res.status(404).json({error:'Pending application not found'});return res.json(updated);});
admin.get('/products',async(_req,res)=>{try{if(mongoDb())return res.json(await mongoDb()!.collection<import('../models/domain').Product>('products').find({}).toArray());}catch{}return res.json(products);});
admin.get('/shops',async(_req,res)=>{try{if(mongoDb())return res.json(await listShops());}catch{}return res.json(shops);});
admin.get('/staff',async(_req,res)=>{try{if(mongoDb())return res.json(await listStaff());}catch{}return res.json(users.filter(u=>u.role!=='customer'));});
admin.get('/orders',async(_req,res)=>{try{if(mongoDb())return res.json(await findOrders());}catch{}return res.json(orders);});
admin.get('/onboarding/applications',async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for onboarding approvals'});const type=typeof req.query.type==='string'?req.query.type:undefined;const status=typeof req.query.status==='string'?req.query.status:'PENDING_REVIEW';const applications=await db.collection('onboardingApplications').find({...(type&&['shopkeeper','employee'].includes(type)?{type:type as PartnerApplicationType}:{}),...(status?{status}:{})}).sort({submittedAt:-1}).limit(200).toArray();return res.json(applications);});
admin.patch('/onboarding/applications/:referenceId/status',async(req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for onboarding approvals'});const status=req.body?.status;if(!['APPROVED','REJECTED'].includes(status))return res.status(400).json({error:'Status must be APPROVED or REJECTED'});const updated=await db.collection('onboardingApplications').findOneAndUpdate({referenceId:req.params.referenceId,status:'PENDING_REVIEW'},{$set:{status,reviewedBy:req.user!.id,reviewedAt:new Date().toISOString()}},{returnDocument:'after'});if(!updated)return res.status(404).json({error:'Pending application not found'});return res.json(updated);});
admin.get('/partner-credentials',async(req,res)=>{const kind=req.query.kind==='employee'?'employee':'shopkeeper';try{await ensurePartnerCredentialPools();return res.json({kind,count:100,credentials:await listPartnerCredentialPool(kind)});}catch(error){console.error(error);return res.status(503).json({error:'Unable to prepare credential pool'});}});

admin.post('/onboarding/applications/:referenceId/assign-credential',async(req,res)=>{
  const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for account assignment'});
  try{await ensurePartnerCredentialPools();}catch{return res.status(503).json({error:'Credential pool is unavailable'});}
  const application=await db.collection<any>('onboardingApplications').findOne({referenceId:req.params.referenceId,status:'APPROVED'});if(!application)return res.status(404).json({error:'Approved application not found'});if(application.activatedAt)return res.status(409).json({error:'This application already has an account'});
  const raw=String(req.body?.suffix??'').trim();if(!/^\d{1,4}$/.test(raw))return res.status(400).json({error:'Enter one to four digits; they will be normalized to a four-digit suffix'});const suffix=raw.padStart(4,'0');const slot=Number(suffix);if(slot<1||slot>100)return res.status(400).json({error:'For the pre-built pool, choose a suffix from 0001 to 0100'});
  const shopId=typeof req.body?.shopId==='string'?req.body.shopId.trim():'';if(application.type==='shopkeeper'&&!shopId)return res.status(400).json({error:'Shop ID is required for a shopkeeper'});if(shopId&&!await db.collection('shops').findOne({id:shopId,active:true}))return res.status(400).json({error:'Active shop not found'});
  const kind=application.type as 'shopkeeper'|'employee';const base=await getPartnerCredentialBase(kind,slot);if(!base)return res.status(404).json({error:'Credential slot not found'});if(base.assignedToId)return res.status(409).json({error:'That four-digit suffix is already assigned'});
  const loginId=`${base.baseLoginId}${suffix}`;const password=`${base.basePassword}${suffix}`;if(!/^\d{22}$/.test(loginId)||!/^\d{22}$/.test(password))return res.status(500).json({error:'Credential generator produced an invalid length'});if(await db.collection<User>('users').findOne({username:loginId}))return res.status(409).json({error:'Credential login is already in use'});
  const claimed=await claimPartnerCredential(kind,slot,application.referenceId);if(!claimed)return res.status(409).json({error:'That four-digit suffix was just assigned. Choose another suffix.'});
  const user:User={id:`u-${Date.now()}-${Math.random().toString(36).slice(2,8)}`,name:application.fullName,email:application.email,phone:application.phone,username:loginId,role:kind,shopId:shopId||undefined,active:true,passwordHash:hashPassword(password)};
  try{await createUser(user);await db.collection('onboardingApplications').updateOne({referenceId:application.referenceId},{$set:{activatedAt:new Date().toISOString(),activatedBy:req.user!.id,userId:user.id,credentialSlot:slot,loginId}});}catch(error){await db.collection('partnerCredentialPool').updateOne({kind,slot,assignedToId:application.referenceId},{$unset:{assignedToId:'',assignedAt:''}});throw error;}
  return res.status(201).json({credentials:{loginId,password,slot},user:{id:user.id,name:user.name,role:user.role,shopId:user.shopId},message:'Credential assigned. Share the 22-digit login ID and 22-digit password securely with the applicant.'});
});
admin.post('/onboarding/applications/:referenceId/activate',async(_req,res)=>res.status(410).json({error:'Manual username/password activation has been replaced. Approve the application, then assign a four-digit suffix from Partner Credentials.'}));
admin.get('/sales-imports',async(_req,res)=>{const db=mongoDb();if(!db)return res.status(503).json({error:'MongoDB is required for CSV approvals'});const imports=await db.collection<SalesImport>('salesImports').find({status:'PENDING_REVIEW'}).sort({submittedAt:-1}).limit(100).project({csv:0}).toArray();return res.json(imports);});
admin.post('/sales-imports/:referenceId/approve',async(req,res)=>{try{return res.json(await approveSalesImport(req.params.referenceId,req.user!.id));}catch(error){return res.status(400).json({error:error instanceof Error?error.message:'Unable to approve CSV'});}});
admin.post('/sales-imports/:referenceId/reject',async(req,res)=>{try{return res.json(await rejectSalesImport(req.params.referenceId,req.user!.id,typeof req.body?.reason==='string'?req.body.reason:'Rejected during admin review'));}catch(error){return res.status(400).json({error:error instanceof Error?error.message:'Unable to reject CSV'});}});
