import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import path from 'node:path';
import { api } from './routes/api.ts';
import { auth } from './routes/auth.ts';
import { bootstrap } from './routes/bootstrap.ts';
import { customer } from './routes/customer.ts';
import { admin } from './routes/admin.ts';
import { shopkeeper } from './routes/shopkeeper.ts';
import { shopkeeperPortal } from './routes/shopkeeperPortal.ts';
import { invoices } from './routes/invoices.ts';
import { delivery } from './routes/delivery.ts';
import { ops } from './routes/ops.ts';
import { paymentsRouter, paymentWebhook } from './routes/payments.ts';
import { onboarding } from './routes/onboarding.ts';
import { pickup } from './routes/pickup.ts';
import { features } from './routes/features.ts';
import { inventory } from './routes/inventory.ts';
import { orderCancellation } from './routes/orderCancellation.ts';
import { rewards } from './routes/rewards.ts';
import { erpInventory } from './routes/erpInventory.ts';
import { erpProcurement } from './routes/erpProcurement.ts';
import { productionOps } from './routes/productionOps.ts';
import { subscriptionsRouter } from './routes/subscriptions.ts';
import { fefoExpiryRouter } from './routes/fefoExpiry.ts';
import { connectMongo, closeMongo, mongoDb } from './db/mongodb.ts';
import { rateLimit } from './middleware/rateLimit.ts';

export const app = express();
const port = Number(process.env.STANDALONE_SERVER === 'true' && process.env.PORT ? process.env.PORT : 3000);
const isProduction = process.env.NODE_ENV === 'production';
const clientOrigin = process.env.CLIENT_ORIGIN;
app.disable('x-powered-by'); app.set('trust proxy', 1);
const allowedOrigins = clientOrigin?.split(',').map(origin => origin.trim()).filter(Boolean) ?? [];
app.use(cors({ origin: (origin, callback) => { if (!origin) return callback(null, true); if (allowedOrigins.includes(origin)) return callback(null, true); if (!isProduction && allowedOrigins.length === 0 && /^https?:\/\/localhost(?::\d+)?$/.test(origin)) return callback(null, true); return callback(new Error('CORS origin not allowed')); }, credentials: true }));
app.use((_req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');next();});
app.use('/api/payments/webhook',express.raw({type:'application/json',limit:'1mb'}),paymentWebhook); app.use(express.json({limit:'2mb'}));
app.get('/health',(_req,res)=>res.status(200).json({status:'ok',service:'freshcart-api'})); app.get('/api',(_req,res)=>res.status(200).json({ok:true,service:'freshcart-api',message:'API is running'}));
app.get('/ready',(_req,res)=>{const ready=Boolean(mongoDb());return res.status(ready?200:503).json({status:ready?'ready':'not_ready',database:ready?'connected':'disconnected'});});
app.get('/api/config',(_req,res)=>res.json({databaseConfigured:Boolean(process.env.MONGODB_URI),environment:process.env.NODE_ENV??'development'}));
app.use(async(_req,_res,next)=>{if(!process.env.VERCEL||mongoDb())return next();try{await connectMongo()}catch(error){console.error('MongoDB request initialization failed:',error)}next()});
app.use('/api',rateLimit({windowMs:60*1000,max:300})); app.use('/api/auth',rateLimit({windowMs:5*60*1000,max:200}),auth); app.use('/api/onboarding',rateLimit({windowMs:15*60*1000,max:60}),onboarding); app.use('/api/shopkeeper-portal',rateLimit({windowMs:60*1000,max:200}),shopkeeperPortal);
app.use('/api',invoices); app.use('/api',inventory); app.use('/api',orderCancellation); app.use('/api/features/rewards',rewards); app.use('/api/erp/inventory',erpInventory); app.use('/api/erp/procurement',erpProcurement); app.use('/api/subscriptions',subscriptionsRouter); app.use('/api/fefo-expiry',fefoExpiryRouter); app.use('/api',productionOps); app.use('/api',api); app.use('/api/bootstrap',bootstrap); app.use('/api/customer',customer); app.use('/api/admin',admin); app.use('/api/shopkeeper',shopkeeper); app.use('/api/delivery',delivery); app.use('/api/ops',ops); app.use('/api/payments',paymentsRouter); app.use('/api/pickup',pickup); app.use('/api/features',features);

export async function startServer() { if (process.env.MONGODB_URI) { try { const db = await connectMongo(); if (db) console.log(`FreshCart MongoDB connected: ${db.databaseName}`); } catch (error) { console.warn('MongoDB connection failed, falling back to in-memory store:', error); } } const server = app.listen(port, '0.0.0.0', () => console.log(`FreshCart API listening on port ${port}`)); const shutdown = async () => { server.close(async () => { await closeMongo(); process.exit(0); }); }; process.once('SIGINT', shutdown); process.once('SIGTERM', shutdown); return server; }
const isMain = process.env.STANDALONE_SERVER === 'true' || (process.argv[1] ? /server\/index(\.[cm]?[jt]s)?$/.test(process.argv[1]) : false);
if (isMain) void startServer();
