import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Bell, Boxes, Clock3, Heart, History, MapPin, PackageCheck, Percent, Search, Settings2, ShieldCheck, ShoppingCart, Sparkles, Star, Store, Truck, Users, Wallet, X } from 'lucide-react';
import { api, type ApiNotification, type ApiOrder, type ApiProduct, type ApiShop, type ApiUser } from '../services/api';

type FeatureRole = 'customer' | 'shopkeeper' | 'employee' | 'admin';

const fuzzyScore = (needle: string, haystack: string) => {
  const n = needle.trim().toLowerCase(); const h = haystack.toLowerCase();
  if (!n) return 1; if (h.includes(n)) return 100 - h.indexOf(n);
  let i = 0; let score = 0;
  for (const ch of n) { const at = h.indexOf(ch, i); if (at < 0) return 0; score += at === i ? 4 : 1; i = at + 1; }
  return score;
};

const money = (n: number) => `₹${Math.round(n).toLocaleString('en-IN')}`;

export function FeatureCenter({ role, products, orders, shops, flash }: { role: FeatureRole; products: ApiProduct[]; orders: ApiOrder[]; shops: ApiShop[]; flash: (message: string) => void }) {
  if (role === 'customer') return <CustomerFeatureCenter products={products} orders={orders} shops={shops} flash={flash} />;
  if (role === 'shopkeeper') return <ShopkeeperFeatureCenter products={products} orders={orders} flash={flash} />;
  if (role === 'employee') return <EmployeeFeatureCenter orders={orders} flash={flash} />;
  return <AdminFeatureCenter orders={orders} shops={shops} flash={flash} />;
}

function Shell({ children, title, eyebrow, onClose }: { children: ReactNode; title: string; eyebrow: string; onClose?: () => void }) {
  return <section className="mx-auto max-w-[1500px] px-4 pt-5 sm:px-6 lg:px-8"><div className="rounded-[28px] border border-black/5 bg-white p-5 shadow-sm sm:p-6"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="text-[10px] font-extrabold uppercase tracking-[.18em] text-[#7b8a82]">{eyebrow}</p><h2 className="heading mt-1 text-2xl font-extrabold text-[#173d2e]">{title}</h2></div>{onClose && <button onClick={onClose} className="rounded-xl bg-[#f3f5f0] p-2"><X size={18}/></button>}</div>{children}</div></section>;
}

function CustomerFeatureCenter({ products, orders, shops, flash }: { products: ApiProduct[]; orders: ApiOrder[]; shops: ApiShop[]; flash: (message: string) => void }) {
  const [tab, setTab] = useState<'discover'|'wishlist'|'recent'|'offers'|'alerts'>('discover');
  const [search, setSearch] = useState('');
  const [liked, setLiked] = useState<string[]>(() => JSON.parse(localStorage.getItem('freshcart_wishlist') || '[]'));
  const [recent, setRecent] = useState<string[]>(() => JSON.parse(localStorage.getItem('freshcart_recent') || '[]'));
  const [notifications, setNotifications] = useState<ApiNotification[]>([]);
  const [coupon, setCoupon] = useState('');
  const [couponMessage, setCouponMessage] = useState('');
  const [selectedShop, setSelectedShop] = useState('');

  useEffect(() => { void api.notifications().then(setNotifications).catch(() => setNotifications([])); }, []);
  useEffect(() => { localStorage.setItem('freshcart_wishlist', JSON.stringify(liked)); }, [liked]);
  const results = useMemo(() => products.map(p => ({ p, score: fuzzyScore(search, `${p.name} ${p.category} ${p.sku}`) })).filter(x => x.score > 0).sort((a,b) => b.score-a.score).slice(0, 8), [products, search]);
  const recentProducts = recent.map(id => products.find(p => p.id === id)).filter(Boolean) as ApiProduct[];
  const wishlist = liked.map(id => products.find(p => p.id === id)).filter(Boolean) as ApiProduct[];
  const markViewed = (id: string) => { const next = [id, ...recent.filter(x => x !== id)].slice(0, 12); setRecent(next); };
  const toggleLike = (id: string) => setLiked(v => v.includes(id) ? v.filter(x => x !== id) : [...v, id]);
  const applyCoupon = () => { const code = coupon.trim().toUpperCase(); const valid = ['FRESH10','WELCOME100','DAIRY5']; if (!valid.includes(code)) { setCouponMessage('Invalid or expired promo code.'); return; } setCouponMessage(code === 'WELCOME100' ? '₹100 off on eligible first orders.' : `${code} applied — offer will be validated at checkout.`); };
  const openSearch = () => document.querySelector<HTMLInputElement>('input[placeholder*="Search fruits"]')?.focus();

  return <Shell eyebrow="Customer experience" title="Everything you need, in one place"><div className="flex flex-wrap gap-2">{[['discover','Smart Search'],['wishlist','Wishlist'],['recent','Recently Viewed'],['offers','Coupons & Delivery'],['alerts','Notifications']].map(([id,label])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={`rounded-full px-4 py-2 text-xs font-extrabold ${tab===id?'bg-[#173d2e] text-white':'bg-[#f1f4ef] text-[#4c6257]'}`}>{label}</button>)}</div>
    {tab==='discover' && <div className="mt-5"><div className="rounded-3xl bg-[#f7faf4] p-5"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#819087]" size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try “banan”, “tomato”, “dairy”..." className="w-full rounded-2xl border border-black/5 bg-white py-3 pl-10 pr-4 text-sm outline-none"/></div><div className="mt-3 text-xs text-[#74847a]">Typo-tolerant ranking across product name, category and SKU.</div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{results.map(({p})=><ProductMini key={p.id} p={p} liked={liked.includes(p.id)} onLike={()=>toggleLike(p.id)} onView={()=>markViewed(p.id)}/>)}</div>{!results.length&&<div className="py-8 text-center text-sm text-[#849189]">No close matches yet.</div>}</div></div>}
    {tab==='wishlist' && <PanelGrid title={`${wishlist.length} favourites`} icon={<Heart size={18}/>}>{wishlist.length ? wishlist.map(p=><ProductMini key={p.id} p={p} liked onLike={()=>toggleLike(p.id)} onView={()=>markViewed(p.id)}/>) : <Empty text="Your wishlist is empty. Tap the heart on any product to save it."/>}</PanelGrid>}
    {tab==='recent' && <PanelGrid title="Recently viewed" icon={<History size={18}/>}>{recentProducts.length ? recentProducts.map(p=><ProductMini key={p.id} p={p} liked={liked.includes(p.id)} onLike={()=>toggleLike(p.id)} onView={()=>markViewed(p.id)}/>) : <Empty text="Products you open will appear here."/>}</PanelGrid>}
    {tab==='offers' && <div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-[#f7faf4] p-5"><div className="flex items-center gap-2 font-extrabold text-[#173d2e]"><Percent size={18}/> Coupons & promo codes</div><div className="mt-4 flex gap-2"><input value={coupon} onChange={e=>setCoupon(e.target.value)} placeholder="FRESH10" className="min-w-0 flex-1 rounded-2xl border border-black/5 bg-white px-4 py-3 text-sm"/><button onClick={applyCoupon} className="rounded-2xl bg-[#173d2e] px-4 py-3 text-xs font-extrabold text-white">Apply</button></div><p className="mt-3 text-xs text-[#718078]">Try FRESH10, WELCOME100 or DAIRY5. Final eligibility is checked server-side during checkout.</p>{couponMessage&&<div className="mt-3 rounded-2xl bg-white p-3 text-xs font-bold text-[#3e6d56]">{couponMessage}</div>}</div><div className="rounded-3xl bg-[#eef5e8] p-5"><div className="flex items-center gap-2 font-extrabold text-[#173d2e]"><Truck size={18}/> Delivery savings</div><p className="mt-3 text-sm font-extrabold text-[#315245]">Free delivery above ₹499</p><p className="mt-1 text-xs text-[#74847a]">Below the threshold, the delivery fee is shown transparently before you pay. Self-pickup has ₹0 delivery fee.</p><div className="mt-4 flex items-center gap-2 text-xs font-bold"><Store size={16}/> {shops.length} connected local shops</div></div></div>}
    {tab==='alerts' && <div className="mt-5 space-y-2">{notifications.length ? notifications.slice(0,10).map(n=><div key={n.id} className={`flex items-start gap-3 rounded-2xl p-4 ${n.read?'bg-[#f7f8f5]':'bg-[#eef5e8]'}`}><Bell size={18} className="mt-0.5 text-[#3e6d56]"/><div className="flex-1"><div className="text-sm font-extrabold text-[#203229]">{n.title}</div><div className="mt-1 text-xs text-[#6f7e76]">{n.message}</div></div>{!n.read&&<button onClick={()=>void api.markNotificationRead(n.id).then(()=>setNotifications(v=>v.map(x=>x.id===n.id?{...x,read:true}:x))).catch(()=>flash('Could not mark notification as read'))} className="text-[10px] font-extrabold text-[#3e6d56]">MARK READ</button>}</div>) : <Empty text="You're all caught up. New order and offer notifications will appear here."/>}</div>}
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><Info title="Orders tracked" value={String(orders.length)} icon={<PackageCheck/>}/><Info title="Saved favourites" value={String(liked.length)} icon={<Heart/>}/><Info title="Delivery addresses" value="Multiple" icon={<MapPin/>}/></div>
  </Shell>;
}

function ProductMini({ p, liked, onLike, onView }: { p: ApiProduct; liked: boolean; onLike: () => void; onView: () => void; key?: any }) { return <div onClick={onView} className="flex items-center gap-3 rounded-2xl bg-white p-3 shadow-sm"><div className="flex h-12 w-12 shrink-0 items-center justify-center overflow-hidden rounded-xl bg-[#edf2e9]">{p.imageUrl?<img src={p.imageUrl} alt="" className="h-full w-full object-cover"/>:<span>🛒</span>}</div><div className="min-w-0 flex-1"><div className="truncate text-xs font-extrabold text-[#203229]">{p.name}</div><div className="mt-1 text-[10px] text-[#7b897f]">{p.category} • {p.unit}</div><div className="mt-1 text-xs font-extrabold text-[#173d2e]">{money(p.sellingPrice)}</div></div><button onClick={e=>{e.stopPropagation();onLike()}} className="rounded-xl bg-[#f1f4ef] p-2 text-[#3e6d56]"><Heart size={16} fill={liked?'currentColor':'none'}/></button></div> }
function PanelGrid({ title, icon, children }: { title: string; icon: ReactNode; children: ReactNode }) { return <div className="mt-5"><div className="flex items-center gap-2 text-sm font-extrabold text-[#315245]">{icon}{title}</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{children}</div></div> }
function Empty({ text }: { text: string }) { return <div className="rounded-2xl bg-[#f7f8f5] p-6 text-center text-xs text-[#7b887f] sm:col-span-2">{text}</div> }
function Info({ title, value, icon }: { title: string; value: string; icon: ReactNode }) { return <div className="rounded-2xl bg-[#f7f8f5] p-4"><div className="text-[#4d705e]">{icon}</div><div className="mt-2 text-[10px] font-bold uppercase tracking-wider text-[#87938c]">{title}</div><div className="mt-1 text-lg font-extrabold text-[#173d2e]">{value}</div></div> }

function ShopkeeperFeatureCenter({ products, orders, flash }: { products: ApiProduct[]; orders: ApiOrder[]; flash: (message: string) => void }) {
  const [tab,setTab]=useState<'inventory'|'orders'|'pricing'|'settings'>('inventory');
  const [stock,setStock]=useState<Record<string,string>>({});
  const shopProducts=products;
  const low=shopProducts.filter(p=>p.stock<=p.minStock);
  const sales=orders.reduce((s,o)=>s+o.total,0); const cost=orders.reduce((s,o)=>s+o.items.reduce((x,i)=>x+i.quantity*(shopProducts.find(p=>p.id===i.productId)?.costPrice??i.unitPrice*0.75),0),0);
  const update=(p:ApiProduct)=>{const value=Number(stock[p.id]??p.stock); if(!Number.isFinite(value)||value<0){flash('Enter a valid stock quantity');return;} void api.updateStock(p.id,value).then(()=>flash(`${p.name} stock updated`)).catch(e=>flash(e instanceof Error?e.message:'Stock update failed'));};
  const status=(id:string,s:'ACCEPTED'|'PICKING'|'PACKING'|'READY'|'CANCELLED')=>void api.updateOrderStatus(id,s).then(()=>flash(`Order ${id} → ${s}`)).catch(e=>flash(e instanceof Error?e.message:'Order update failed'));
  return <Shell eyebrow="Shopkeeper control center" title="Run your shop"><div className="flex flex-wrap gap-2">{[['inventory','Inventory'],['orders','Orders'],['pricing','Discounts & delivery'],['settings','Operating settings']].map(([id,label])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={`rounded-full px-4 py-2 text-xs font-extrabold ${tab===id?'bg-[#173d2e] text-white':'bg-[#f1f4ef] text-[#4c6257]'}`}>{label}</button>)}</div>
    {tab==='inventory'&&<div className="mt-5"><div className="grid gap-3 md:grid-cols-4"><Info title="Products" value={String(shopProducts.length)} icon={<Boxes/>}/><Info title="Low stock" value={String(low.length)} icon={<Bell/>}/><Info title="Sales" value={money(sales)} icon={<Wallet/>}/><Info title="Est. profit" value={money(sales-cost)} icon={<Sparkles/>}/></div><div className="mt-4 rounded-3xl bg-[#fff9e9] p-4 text-xs font-bold text-[#775e23]">{low.length?`Low-stock alert: ${low.slice(0,4).map(p=>p.name).join(', ')}${low.length>4?'…':''}`:'Inventory healthy — no items below minimum threshold.'}</div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-xs"><thead><tr className="border-b text-[#7b887f]"><th className="p-3">Product</th><th>Stock</th><th>Minimum</th><th>Status</th><th>Update</th></tr></thead><tbody>{shopProducts.slice(0,50).map(p=><tr key={p.id} className="border-b border-black/5"><td className="p-3 font-extrabold">{p.name}</td><td>{p.stock}</td><td>{p.minStock}</td><td className={p.stock<=p.minStock?'font-extrabold text-amber-700':'text-emerald-700'}>{p.stock<=p.minStock?'LOW':'OK'}</td><td><div className="flex gap-2"><input value={stock[p.id]??p.stock} onChange={e=>setStock(v=>({...v,[p.id]:e.target.value}))} className="w-20 rounded-lg border px-2 py-1"/><button onClick={()=>update(p)} className="rounded-lg bg-[#173d2e] px-3 py-1 text-white">Save</button></div></td></tr>)}</tbody></table></div></div>}
    {tab==='orders'&&<div className="mt-5 space-y-3">{orders.length?orders.map(o=><div key={o.id} className="rounded-2xl bg-[#f7f8f5] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><div className="text-sm font-extrabold">#{o.id}</div><div className="text-xs text-[#7b887f]">{o.items.length} line items • {money(o.total)}</div></div><span className="rounded-full bg-white px-3 py-1 text-[10px] font-extrabold">{o.status}</span></div><div className="mt-3 flex flex-wrap gap-2">{(['ACCEPTED','PICKING','PACKING','READY','CANCELLED'] as const).map(s=><button key={s} onClick={()=>status(o.id,s)} className="rounded-xl bg-white px-3 py-2 text-[10px] font-extrabold text-[#315245]">{s}</button>)}</div></div>):<Empty text="No shop orders yet."/>}</div>}
    {tab==='pricing'&&<div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-[#f7faf4] p-5"><div className="flex items-center gap-2 font-extrabold"><Percent size={18}/> Discount management</div><p className="mt-2 text-xs text-[#74847a]">Use product MRP vs selling price for instant markdowns. Keep discounts within your approved shop pricing policy.</p><div className="mt-4 space-y-2">{shopProducts.filter(p=>p.mrp>p.sellingPrice).slice(0,8).map(p=><div key={p.id} className="flex justify-between rounded-xl bg-white p-3 text-xs"><span className="font-bold">{p.name}</span><span className="font-extrabold">{Math.round((1-p.sellingPrice/p.mrp)*100)}% off</span></div>)}</div></div><div className="rounded-3xl bg-[#eef5e8] p-5"><div className="font-extrabold text-[#173d2e]">Delivery settings</div><div className="mt-4 space-y-3 text-xs"><label className="flex items-center justify-between">Minimum order <input defaultValue="199" className="w-24 rounded-xl border px-3 py-2"/></label><label className="flex items-center justify-between">Free delivery above <input defaultValue="499" className="w-24 rounded-xl border px-3 py-2"/></label><label className="flex items-center justify-between">Delivery radius <input defaultValue="8 km" className="w-24 rounded-xl border px-3 py-2"/></label></div></div></div>}
    {tab==='settings'&&<div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-[#f7faf4] p-5"><div className="flex items-center gap-2 font-extrabold"><Clock3 size={18}/> Operating hours</div><div className="mt-4 grid grid-cols-2 gap-2">{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map(d=><label key={d} className="rounded-xl bg-white p-3 text-xs"><span className="font-bold">{d}</span><input defaultValue="08:00 – 22:00" className="mt-2 w-full rounded-lg border px-2 py-1"/></label>)}</div></div><div className="rounded-3xl bg-[#f7faf4] p-5"><div className="flex items-center gap-2 font-extrabold"><Settings2 size={18}/> Bulk upload & image management</div><p className="mt-2 text-xs text-[#74847a]">CSV imports, image URLs, SKU/barcode, cost, MRP and selling price are supported by the catalogue workflow.</p><div className="mt-4 rounded-2xl border-2 border-dashed border-[#cad6cb] p-6 text-center text-xs font-bold text-[#708078]">Drop CSV here or choose a file</div></div></div>}
  </Shell>;
}

function EmployeeFeatureCenter({ orders, flash }: { orders: ApiOrder[]; flash: (message: string) => void }) {
  const [tab,setTab]=useState<'queue'|'attendance'|'earnings'|'history'>('queue');
  const [attendance,setAttendance]=useState<{checkIn?:string;checkOut?:string;status:string}|null>(null);
  useEffect(()=>{void api.attendance().then(v=>setAttendance(v[0]??null)).catch(()=>undefined)},[]);
  const deliveryOrders=orders.filter(o=>['READY','OUT_FOR_DELIVERY','DELIVERED','COLLECTED'].includes(o.status));
  const nextStatus=(o:ApiOrder)=>{const next=o.status==='READY'?'OUT_FOR_DELIVERY':o.status==='OUT_FOR_DELIVERY'?'DELIVERED':null;if(!next)return;void api.deliveryStatus(o.id,next).then(()=>flash(`Delivery ${o.id} → ${next}`)).catch(e=>flash(e instanceof Error?e.message:'Status update failed'));};
  return <Shell eyebrow="Employee / delivery" title="Delivery operations"><div className="flex flex-wrap gap-2">{[['queue','Assigned orders'],['attendance','Attendance'],['earnings','Daily performance'],['history','Delivery history']].map(([id,label])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={`rounded-full px-4 py-2 text-xs font-extrabold ${tab===id?'bg-[#173d2e] text-white':'bg-[#f1f4ef] text-[#4c6257]'}`}>{label}</button>)}</div>
    {tab==='queue'&&<div className="mt-5 space-y-3">{deliveryOrders.length?deliveryOrders.map(o=><div key={o.id} className="rounded-2xl bg-[#f7f8f5] p-4"><div className="flex items-center justify-between"><div><div className="text-sm font-extrabold">#{o.id}</div><div className="mt-1 text-xs text-[#748078]">Customer contact/details available from the protected delivery record.</div></div><span className="rounded-full bg-white px-3 py-1 text-[10px] font-extrabold">{o.status}</span></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>flash('Open the delivery detail from the assigned-order dashboard for protected customer contact data.')} className="rounded-xl bg-white px-3 py-2 text-[10px] font-extrabold">Customer details</button><button onClick={()=>nextStatus(o)} className="rounded-xl bg-[#173d2e] px-3 py-2 text-[10px] font-extrabold text-white">Advance status</button><button onClick={()=>flash('Proof-of-delivery capture is ready to connect to the delivery photo/signature endpoint.')} className="rounded-xl bg-white px-3 py-2 text-[10px] font-extrabold">Proof of delivery</button></div></div>):<Empty text="No assigned deliveries in the current queue."/>}</div>}
    {tab==='attendance'&&<div className="mt-5 grid gap-4 md:grid-cols-2"><div className="rounded-3xl bg-[#f7faf4] p-5"><div className="font-extrabold">Today</div><div className="mt-2 text-xs text-[#748078]">{attendance?.status??'No attendance record yet.'}</div><div className="mt-4 flex gap-2"><button onClick={()=>void api.checkIn().then(v=>{setAttendance(v);flash('Checked in successfully')}).catch(e=>flash(e instanceof Error?e.message:'Check-in failed'))} className="rounded-xl bg-[#173d2e] px-4 py-3 text-xs font-extrabold text-white">Check in</button><button onClick={()=>void api.checkOut().then(v=>{setAttendance(v);flash('Checked out successfully')}).catch(e=>flash(e instanceof Error?e.message:'Check-out failed'))} className="rounded-xl bg-white px-4 py-3 text-xs font-extrabold">Check out</button></div></div><div className="rounded-3xl bg-[#eef5e8] p-5"><div className="font-extrabold">Notifications</div><p className="mt-2 text-xs text-[#748078]">Delivery assignment and status notifications are surfaced through the notification service.</p></div></div>}
    {tab==='earnings'&&<div className="mt-5 grid gap-3 sm:grid-cols-3"><Info title="Completed" value={String(deliveryOrders.filter(o=>o.status==='DELIVERED').length)} icon={<PackageCheck/>}/><Info title="Performance" value={`${Math.min(100,deliveryOrders.length*12)}%`} icon={<Star/>}/><Info title="Est. earnings" value={money(deliveryOrders.filter(o=>o.status==='DELIVERED').length*40)} icon={<Wallet/>}/></div>}
    {tab==='history'&&<div className="mt-5 space-y-2">{deliveryOrders.filter(o=>o.status==='DELIVERED').map(o=><div key={o.id} className="flex justify-between rounded-2xl bg-[#f7f8f5] p-4 text-xs"><span className="font-extrabold">#{o.id}</span><span className="text-[#718078]">Delivered • {new Date(o.createdAt).toLocaleString()}</span></div>)}{!deliveryOrders.some(o=>o.status==='DELIVERED')&&<Empty text="Completed delivery history will appear here."/>}</div>}
  </Shell>;
}

function AdminFeatureCenter({ orders, shops, flash }: { orders: ApiOrder[]; shops: ApiShop[]; flash: (message: string) => void }) {
  const [tab,setTab]=useState<'overview'|'shops'|'customers'|'staff'|'audit'|'security'>('overview');
  const [staff,setStaff]=useState<ApiUser[]>([]);
  useEffect(()=>{void api.adminStaff().then(setStaff).catch(()=>undefined)},[]);
  const sales=orders.reduce((s,o)=>s+o.total,0); const profit=orders.reduce((s,o)=>s+o.items.reduce((x,i)=>x+i.quantity*(i.unitPrice*.25),0),0);
  return <Shell eyebrow="Super Admin / platform" title="Platform command center"><div className="flex flex-wrap gap-2">{[['overview','Analytics'],['shops','All shops'],['customers','Customers'],['staff','Employees'],['audit','Audit logs'],['security','Security']].map(([id,label])=><button key={id} onClick={()=>setTab(id as typeof tab)} className={`rounded-full px-4 py-2 text-xs font-extrabold ${tab===id?'bg-[#173d2e] text-white':'bg-[#f1f4ef] text-[#4c6257]'}`}>{label}</button>)}</div>
    {tab==='overview'&&<div className="mt-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Info title="Platform sales" value={money(sales)} icon={<Wallet/>}/><Info title="Estimated profit" value={money(profit)} icon={<Sparkles/>}/><Info title="Orders" value={String(orders.length)} icon={<PackageCheck/>}/><Info title="Shops" value={String(shops.length)} icon={<Store/>}/></div><div className="mt-5 rounded-3xl bg-[#173d2e] p-5 text-white"><div className="flex items-center gap-2 font-extrabold"><ShieldCheck size={18}/> Production security baseline</div><div className="mt-3 grid gap-2 text-xs text-white/80 sm:grid-cols-2"><div>✓ Role-based access controls</div><div>✓ Request rate limiting</div><div>✓ JWT authentication</div><div>✓ Input validation on critical mutations</div><div>✓ Secure response headers</div><div>✓ Audit-ready event surfaces</div></div></div></div>}
    {tab==='shops'&&<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{shops.map(s=><div key={s.id} className="rounded-2xl bg-[#f7f8f5] p-4"><div className="flex items-center gap-2"><Store size={17}/><span className="font-extrabold">{s.name}</span></div><div className="mt-2 text-xs text-[#748078]">{s.address}</div><div className="mt-3 flex justify-between text-[10px] font-extrabold"><span>{s.active?'ACTIVE':'INACTIVE'}</span><button onClick={()=>flash('Shop activation is controlled from the protected admin account manager.')} className="text-[#3e6d56]">MANAGE</button></div></div>)}</div>}
    {tab==='customers'&&<div className="mt-5 rounded-2xl bg-[#f7f8f5] p-5"><div className="flex items-center gap-2 font-extrabold"><Users size={18}/> Customer visibility</div><p className="mt-2 text-xs text-[#748078]">Customer accounts, orders and addresses are exposed only through authenticated admin APIs. Use the existing Admin ERP customer view for detailed records.</p><div className="mt-4 text-2xl font-extrabold text-[#173d2e]">{new Set(orders.map(o=>o.customerId)).size} active-order customers</div></div>}
    {tab==='staff'&&<div className="mt-5 space-y-2">{staff.map(u=><div key={u.id} className="flex items-center justify-between rounded-2xl bg-[#f7f8f5] p-4"><div><div className="text-sm font-extrabold">{u.name}</div><div className="text-xs text-[#748078]">{u.role} • {u.phone}</div></div><span className={`rounded-full px-3 py-1 text-[10px] font-extrabold ${u.active?'bg-[#e7f3e7] text-emerald-700':'bg-[#f5e8e8] text-red-700'}`}>{u.active?'ACTIVE':'INACTIVE'}</span></div>)}</div>}
    {tab==='audit'&&<div className="mt-5 rounded-2xl bg-[#f7f8f5] p-5"><div className="flex items-center gap-2 font-extrabold"><History size={18}/> Audit trail</div><p className="mt-2 text-xs text-[#748078]">Administrative mutations are routed through authenticated APIs. Keep MongoDB audit records on a dedicated retention policy and export them for compliance/recovery.</p><div className="mt-4 space-y-2">{orders.slice(0,8).map(o=><div key={o.id} className="rounded-xl bg-white p-3 text-xs"><span className="font-extrabold">ORDER {o.id}</span> <span className="text-[#7a887f]">{o.status} • {new Date(o.createdAt).toLocaleString()}</span></div>)}</div></div>}
    {tab==='security'&&<div className="mt-5 grid gap-3 md:grid-cols-2"><SecurityItem title="RBAC" text="Protected routes enforce customer, shopkeeper, employee and admin roles."/><SecurityItem title="Session hardening" text="JWT expiry and active-account checks are enforced by the auth layer."/><SecurityItem title="Rate limiting" text="Global and sensitive auth/onboarding endpoints are rate-limited."/><SecurityItem title="Validation" text="Critical stock, order and credential mutations validate inputs before writes."/><SecurityItem title="Database indexes" text="Keep unique phone identity and operational lookup indexes synchronized during migrations."/><SecurityItem title="Backup & recovery" text="Use automated MongoDB backups, point-in-time recovery and restore drills before launch."/></div>}
  </Shell>;
}
function SecurityItem({title,text}:{title:string;text:string}){return <div className="rounded-2xl bg-[#f7faf4] p-4"><div className="flex items-center gap-2 text-sm font-extrabold text-[#173d2e]"><ShieldCheck size={17}/>{title}</div><div className="mt-2 text-xs leading-5 text-[#748078]">{text}</div></div>}
