import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { api, type PartnerCredential, type SuperApplication, type SuperDashboard } from '../services/api';
import { BarChart3, CheckCircle2, Clock3, Copy, KeyRound, LogOut, RefreshCw, ShieldCheck, Store, TrendingUp, Users, XCircle } from 'lucide-react';

const money = (n:number) => `₹${Math.round(n).toLocaleString('en-IN')}`;
type CredentialKind = 'shopkeeper' | 'employee';

export function SuperAdminPortal({ onLogout }:{ onLogout:()=>void }) {
  const [dashboard,setDashboard]=useState<SuperDashboard|null>(null);
  const [applications,setApplications]=useState<SuperApplication[]>([]);
  const [pool,setPool]=useState<PartnerCredential[]>([]);
  const [poolKind,setPoolKind]=useState<CredentialKind>('shopkeeper');
  const [tab,setTab]=useState<'overview'|'approvals'|'credentials'>('overview');
  const [loading,setLoading]=useState(true);
  const [poolLoading,setPoolLoading]=useState(false);
  const [message,setMessage]=useState('');
  const [credential,setCredential]=useState<{loginId:string;password:string}|null>(null);
  const [assigning,setAssigning]=useState<string|null>(null);
  const [slots,setSlots]=useState<Record<string,string>>({});
  const [copied,setCopied]=useState('');

  const loadPool=async(kind:CredentialKind=poolKind)=>{
    setPoolLoading(true);
    try { const result=await api.partnerCredentials(kind); setPool(result.credentials); }
    catch(e){ setPool([]); setMessage(e instanceof Error?e.message:'Unable to load credential pool'); }
    finally { setPoolLoading(false); }
  };

  const load=async()=>{
    setLoading(true); setMessage('');
    const [dashboardResult,applicationsResult,poolResult]=await Promise.allSettled([api.superDashboard(),api.superApplications(),api.partnerCredentials(poolKind)]);
    if(dashboardResult.status==='fulfilled') setDashboard(dashboardResult.value); else setMessage(dashboardResult.reason instanceof Error?dashboardResult.reason.message:'Unable to load business overview');
    if(applicationsResult.status==='fulfilled') setApplications(applicationsResult.value); else if(dashboardResult.status==='fulfilled') setMessage('Business Overview is available. Approval queue needs MongoDB connectivity.');
    if(poolResult.status==='fulfilled') setPool(poolResult.value.credentials); else if(dashboardResult.status==='fulfilled' && applicationsResult.status==='fulfilled') setMessage('Credential pool needs MongoDB connectivity.');
    setLoading(false);
  };
  useEffect(()=>{void load();},[]);
  useEffect(()=>{ if(!loading) void loadPool(poolKind); },[poolKind]);

  const approve=async(ref:string,status:'APPROVED'|'REJECTED')=>{
    try { const updated=await api.superApplicationStatus(ref,status); setApplications(current=>current.map(app=>app.referenceId===ref?updated:app)); setMessage(status==='APPROVED'?'Application approved. Enter a four-digit suffix to create the account.':'Application rejected.'); setDashboard(await api.superDashboard()); }
    catch(e){setMessage(e instanceof Error?e.message:'Unable to update application');}
  };
  const assign=async(app:SuperApplication)=>{
    const raw=(slots[app.referenceId]||'').replace(/\D/g,'').slice(0,4); const slot=Number(raw);
    if(!/^\d{1,4}$/.test(raw)||!Number.isInteger(slot)||slot<1||slot>100){setMessage('Choose a four-digit suffix from 0001 to 0100.');return;}
    setAssigning(app.referenceId);
    try { const result=await api.assignPartnerCredential(app.referenceId,slot); setCredential(result.credentials); setApplications(current=>current.map(item=>item.referenceId===app.referenceId?{...item,activatedAt:new Date().toISOString(),loginId:result.credentials.loginId,credentialSlot:result.credentials.slot}:item)); setMessage(`Credential created for ${app.fullName}. Share the 22-digit login ID and password securely.`); setDashboard(await api.superDashboard()); await loadPool(app.type); }
    catch(e){setMessage(e instanceof Error?e.message:'Unable to assign credential');}
    finally{setAssigning(null);}
  };
  const copyValue=async(label:string,value:string)=>{try{await navigator.clipboard.writeText(value);setCopied(label);window.setTimeout(()=>setCopied(''),1500);}catch{setMessage('Clipboard access was blocked by the browser.');}};
  const maxSales=useMemo(()=>Math.max(...(dashboard?.monthly.map(x=>x.sales)??[1]),1),[dashboard]);
  const nav=(next:typeof tab)=>setTab(next);

  return <div className="min-h-screen bg-[#0b1511] text-[#eef5f0]">
    <aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-white/10 bg-[#101c17] p-5 lg:block">
      <Brand/><nav className="mt-10 space-y-2"><NavButton active={tab==='overview'} onClick={()=>nav('overview')} icon={<BarChart3 size={17}/>} label="Business Overview"/><NavButton active={tab==='approvals'} onClick={()=>nav('approvals')} icon={<Users size={17}/>} label={`Approvals & Accounts${dashboard?.totals.pendingApplications?` (${dashboard.totals.pendingApplications})`:''}`}/><NavButton active={tab==='credentials'} onClick={()=>nav('credentials')} icon={<KeyRound size={17}/>} label="Credential Vault"/></nav>
      <button onClick={onLogout} className="absolute bottom-6 left-5 right-5 rounded-2xl border border-white/10 px-4 py-3 text-left text-sm font-bold text-[#a9b9b1] hover:bg-white/5"><LogOut className="mr-3 inline" size={17}/>Sign out</button>
    </aside>
    <main className="lg:ml-64"><header className="sticky top-0 z-20 border-b border-white/10 bg-[#0b1511]/90 px-5 py-5 backdrop-blur sm:px-8"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#8fa49a]">Owner control center</p><h1 className="mt-1 text-2xl font-black">{tab==='overview'?'Business Intelligence':tab==='approvals'?'Approvals & Account Provisioning':'Credential Vault'}</h1></div><div className="flex items-center gap-2 rounded-2xl border border-white/10 px-3 py-2 text-xs font-bold"><ShieldCheck size={16}/> SUPER ADMIN</div></div><div className="mt-4 flex gap-2 overflow-x-auto lg:hidden"><MobileTab active={tab==='overview'} onClick={()=>nav('overview')} label="Overview"/><MobileTab active={tab==='approvals'} onClick={()=>nav('approvals')} label="Approvals"/><MobileTab active={tab==='credentials'} onClick={()=>nav('credentials')} label="Credentials"/><button onClick={onLogout} className="ml-auto rounded-xl bg-white/5 p-2"><LogOut size={16}/></button></div></header>
      <div className="p-5 sm:p-8">
        {message&&<div className="mb-5 rounded-2xl border border-[#d7ef8d]/20 bg-[#d7ef8d]/10 px-4 py-3 text-sm font-semibold text-[#d7ef8d]">{message}</div>}
        {credential&&<CredentialResult credential={credential} copied={copied} copyValue={copyValue} dismiss={()=>setCredential(null)}/>} 
        {loading?<div className="rounded-3xl border border-white/10 p-10 text-center text-[#8fa49a]">Loading secure owner data…</div>:tab==='overview'&&dashboard?<Overview data={dashboard} maxSales={maxSales}/>:tab==='approvals'?<Approvals applications={applications} slots={slots} setSlot={value=>setSlots(s=>({...s,[value.ref]:value.value}))} approve={approve} reject={ref=>void approve(ref,'REJECTED')} assign={assign} assigning={assigning}/>:<CredentialVault pool={pool} kind={poolKind} setKind={setPoolKind} loading={poolLoading} refresh={()=>void loadPool()} copied={copied} copyValue={copyValue}/>} 
      </div>
    </main>
  </div>;
}

function Brand(){return <div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#d7ef8d] text-[#10251b]"><ShieldCheck size={22}/></div><div><div className="font-black tracking-tight">FreshCart</div><div className="text-[10px] uppercase tracking-[.18em] text-[#8fa49a]">Super Admin</div></div></div>}
function NavButton({active,onClick,icon,label}:{active:boolean;onClick:()=>void;icon:ReactNode;label:string}){return <button onClick={onClick} className={`w-full rounded-2xl px-4 py-3 text-left text-sm font-bold ${active?'bg-[#d7ef8d] text-[#10251b]':'text-[#a9b9b1] hover:bg-white/5'}`}>{icon}<span className="ml-3">{label}</span></button>}
function MobileTab({active,onClick,label}:{active:boolean;onClick:()=>void;label:string}){return <button onClick={onClick} className={`rounded-xl px-3 py-2 text-xs font-bold ${active?'bg-[#d7ef8d] text-[#10251b]':'bg-white/5'}`}>{label}</button>}

function CredentialVault({pool,kind,setKind,loading,refresh,copied,copyValue}:{pool:PartnerCredential[];kind:CredentialKind;setKind:(kind:CredentialKind)=>void;loading:boolean;refresh:()=>void;copied:string;copyValue:(label:string,value:string)=>void}){
  const available=pool.filter(row=>!row.assignedToId).length;
  return <section className="space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#8fa49a]">Pre-built credentials</p><h2 className="mt-1 text-xl font-black">18-digit credential vault</h2><p className="mt-2 max-w-2xl text-sm text-[#8fa49a]">Each pool entry contains a unique 18-digit login base and a matching encrypted 18-digit password base. After approval, append the four-digit suffix to create the final 22-digit credentials.</p></div><button onClick={refresh} className="rounded-xl bg-white/5 px-3 py-2 text-xs font-bold"><RefreshCw className="mr-2 inline" size={14}/>Refresh</button></div>
    <div className="grid gap-4 sm:grid-cols-3"><button onClick={()=>setKind('shopkeeper')} className={`rounded-2xl border p-4 text-left ${kind==='shopkeeper'?'border-[#d7ef8d]/50 bg-[#d7ef8d]/10':'border-white/10 bg-[#101c17]'}`}><div className="text-xs text-[#8fa49a]">SHOPKEEPER</div><div className="mt-1 text-2xl font-black">{kind==='shopkeeper'?pool.length:'—'}</div><div className="text-xs text-[#8fa49a]">pre-built slots</div></button><button onClick={()=>setKind('employee')} className={`rounded-2xl border p-4 text-left ${kind==='employee'?'border-[#d7ef8d]/50 bg-[#d7ef8d]/10':'border-white/10 bg-[#101c17]'}`}><div className="text-xs text-[#8fa49a]">EMPLOYEE</div><div className="mt-1 text-2xl font-black">{kind==='employee'?pool.length:'—'}</div><div className="text-xs text-[#8fa49a]">pre-built slots</div></button><div className="rounded-2xl border border-white/10 bg-[#101c17] p-4"><div className="text-xs text-[#8fa49a]">AVAILABLE NOW</div><div className="mt-1 text-2xl font-black">{available}</div><div className="text-xs text-[#8fa49a]">unassigned slots</div></div></div>
    <div className="overflow-hidden rounded-3xl border border-white/10 bg-[#101c17]"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><h3 className="font-black capitalize">{kind} pool</h3><p className="mt-1 text-xs text-[#8fa49a]">Use the slot number as the four-digit suffix when provisioning an approved application.</p></div><span className="rounded-full bg-white/5 px-3 py-1 text-xs font-bold">{available} available</span></div>{loading?<div className="p-10 text-center text-[#8fa49a]">Preparing credential pool…</div>:pool.length===0?<div className="p-10 text-center text-[#8fa49a]">No credential pool is available. Check MongoDB connectivity.</div>:<div className="max-h-[620px] overflow-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="sticky top-0 bg-[#101c17] text-xs uppercase tracking-wider text-[#8fa49a]"><tr><th className="px-5 py-4">Slot</th><th className="px-5 py-4">18-digit Login Base</th><th className="px-5 py-4">Final format</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Action</th></tr></thead><tbody>{pool.map(row=><tr key={row.slot} className="border-t border-white/5"><td className="px-5 py-4 font-black">{String(row.slot).padStart(4,'0')}</td><td className="px-5 py-4 font-mono tracking-wider text-[#d7ef8d]">{row.baseLoginId}</td><td className="px-5 py-4 font-mono text-xs text-[#a9b9b1]">{row.baseLoginId}{String(row.slot).padStart(4,'0')}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black ${row.assignedToId?'bg-white/5 text-[#8fa49a]':'bg-[#d7ef8d] text-[#10251b]'}`}>{row.assignedToId?'ASSIGNED':'AVAILABLE'}</span></td><td className="px-5 py-4"><button onClick={()=>void copyValue(`slot-${row.slot}`,row.baseLoginId)} className="rounded-lg bg-white/5 px-2.5 py-1.5 text-xs font-bold"><Copy className="mr-1 inline" size={12}/>{copied===`slot-${row.slot}`?'Copied':'Copy ID'}</button></td></tr>)}</tbody></table></div>}</div>
    <div className="rounded-2xl border border-amber-200/10 bg-amber-200/5 p-4 text-xs text-[#c6d0ca]"><b className="text-[#d7ef8d]">Password security:</b> password bases are encrypted at rest and are intentionally not dumped into the pool table. The final 22-digit password is revealed once, immediately after you create an account.</div>
  </section>;
}

function CredentialResult({credential,copied,copyValue,dismiss}:{credential:{loginId:string;password:string};copied:string;copyValue:(label:string,value:string)=>void;dismiss:()=>void}){return <div className="mb-6 rounded-3xl border border-[#d7ef8d]/30 bg-[#14251d] p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="text-xs font-bold uppercase tracking-[.15em] text-[#8fa49a]">New partner credentials</div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Secret label="Login ID" value={credential.loginId} copied={copied==='login'} onCopy={()=>void copyValue('login',credential.loginId)}/><Secret label="Password" value={credential.password} copied={copied==='password'} onCopy={()=>void copyValue('password',credential.password)}/></div><p className="mt-3 text-xs text-[#8fa49a]">Both credentials are 22 digits: an 18-digit pre-built base plus the four-digit suffix you selected.</p></div><button onClick={dismiss} className="text-xs font-bold text-[#8fa49a]">Dismiss</button></div></div>}
function Secret({label,value,copied,onCopy}:{label:string;value:string;copied:boolean;onCopy:()=>void}){return <div className="rounded-2xl border border-white/10 bg-[#0b1511] p-3"><div className="text-[10px] font-bold uppercase tracking-wider text-[#8fa49a]">{label}</div><div className="mt-1 break-all font-mono text-base font-black tracking-wider text-[#d7ef8d]">{value}</div><button onClick={onCopy} className="mt-2 rounded-lg bg-white/5 px-2.5 py-1 text-xs font-bold"><Copy className="mr-1 inline" size={12}/>{copied?'Copied':'Copy'}</button></div>}

function Approvals({applications,slots,setSlot,approve,reject,assign,assigning}:{applications:SuperApplication[];slots:Record<string,string>;setSlot:(value:{ref:string;value:string})=>void;approve:(ref:string,status:'APPROVED'|'REJECTED')=>void;reject:(ref:string)=>void;assign:(app:SuperApplication)=>void;assigning:string|null}){return <section><div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-[#8fa49a]">Approval queue</p><h2 className="mt-1 text-xl font-black">Shopkeeper & employee applications</h2></div></div>{applications.length===0?<div className="rounded-3xl border border-white/10 p-10 text-center"><CheckCircle2 className="mx-auto" size={32}/><p className="mt-3 font-bold">No pending applications</p><p className="mt-1 text-xs text-[#8fa49a]">Approved accounts remain available after approval until credentials are created.</p></div>:<div className="grid gap-4">{applications.map(app=><ApplicationCard key={app.referenceId} app={app} slot={slots[app.referenceId]??''} setSlot={value=>setSlot({ref:app.referenceId,value})} approve={()=>approve(app.referenceId,'APPROVED')} reject={()=>reject(app.referenceId)} assign={()=>assign(app)} assigning={assigning===app.referenceId}/>)}</div>}</section>}
function ApplicationCard({app,slot,setSlot,approve,reject,assign,assigning}:{app:SuperApplication;slot:string;setSlot:(v:string)=>void;approve:()=>void;reject:()=>void;assign:()=>void;assigning:boolean;key?:any}){const approved=app.status==='APPROVED';const suffix=slot.padStart(4,'0');return <article className="rounded-3xl border border-white/10 bg-[#101c17] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="rounded-full bg-white/5 px-3 py-1 text-[10px] font-black uppercase tracking-[.12em]">{app.type}</span><span className="text-[11px] text-[#8fa49a]">{app.referenceId}</span></div><h3 className="mt-3 text-lg font-black">{app.fullName}</h3><p className="mt-1 text-sm text-[#a9b9b1]">{app.email} • {app.phone}</p><p className="mt-2 text-xs text-[#8fa49a]">{app.city}, {app.state} • submitted {new Date(app.submittedAt).toLocaleString('en-IN')}</p>{app.businessName&&<p className="mt-2 text-sm font-bold">Business: {app.businessName}</p>}{app.preferredRole&&<p className="mt-1 text-xs text-[#8fa49a]">Preferred role: {app.preferredRole}</p>}</div><span className={`rounded-full px-3 py-1 text-[10px] font-black ${approved?'bg-[#d7ef8d] text-[#10251b]':'bg-amber-200/10 text-amber-200'}`}>{app.status}</span></div>{approved&&!app.activatedAt&&<div className="mt-5 rounded-2xl bg-white/[.03] p-4"><div className="mb-2 text-xs font-bold uppercase tracking-wider text-[#8fa49a]">Generate final 22-digit credentials</div><div className="flex flex-wrap gap-2"><input inputMode="numeric" maxLength={4} value={slot} onChange={e=>setSlot(e.target.value.replace(/\D/g,'').slice(0,4))} placeholder="0001–0100" className="w-44 rounded-xl border border-white/10 bg-[#0b1511] px-3 py-2 text-sm font-mono outline-none"/><button disabled={assigning} onClick={assign} className="rounded-xl bg-[#d7ef8d] px-4 py-2 text-xs font-black text-[#10251b]">{assigning?'Creating…':'Create 22-digit login'}</button></div>{slot&&/^\d{1,4}$/.test(slot)&&Number(suffix)>=1&&Number(suffix)<=100&&<p className="mt-3 text-xs text-[#8fa49a]">Suffix <b className="text-[#d7ef8d]">{suffix}</b> will be appended to the matching 18-digit base in the Credential Vault.</p>}</div>}{!approved&&<div className="mt-5 flex gap-2"><button onClick={approve} className="rounded-xl bg-[#d7ef8d] px-4 py-2 text-xs font-black text-[#10251b]"><CheckCircle2 className="mr-1 inline" size={15}/>Approve</button><button onClick={reject} className="rounded-xl bg-white/5 px-4 py-2 text-xs font-black"><XCircle className="mr-1 inline" size={15}/>Reject</button></div>}{app.activatedAt&&<div className="mt-4 flex items-center gap-2 text-xs font-bold text-[#d7ef8d]"><CheckCircle2 size={15}/>Account created • {app.loginId}</div>}<div className="mt-4 flex items-center gap-2 text-[11px] text-[#8fa49a]"><Clock3 size={14}/>Identity details were submitted with the application and should be verified according to your business process.</div></article>}

function Overview({data,maxSales}:{data:SuperDashboard;maxSales:number}){const cards=[{label:'Total Sales',value:money(data.totals.sales),Icon:TrendingUp},{label:'Profit',value:money(data.totals.profit),Icon:BarChart3},{label:'Profit Margin',value:`${data.totals.margin.toFixed(1)}%`,Icon:TrendingUp},{label:'Orders',value:data.totals.orders.toLocaleString('en-IN'),Icon:Store}];return <div className="space-y-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({label,value,Icon})=><div key={label} className="rounded-3xl border border-white/10 bg-[#101c17] p-5"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-white/5"><Icon size={18}/></div><div className="mt-5 text-xs font-bold uppercase tracking-[.14em] text-[#8fa49a]">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>)}</div><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><div className="rounded-3xl border border-white/10 bg-[#101c17] p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#8fa49a]">Performance</p><h2 className="mt-1 text-lg font-black">Monthly sales</h2></div><TrendingUp size={20}/></div><div className="mt-8 space-y-4">{data.monthly.map(row=><div key={row.month}><div className="mb-1 flex justify-between text-xs"><span className="font-bold">{row.month}</span><span>{money(row.sales)}</span></div><div className="h-3 overflow-hidden rounded-full bg-white/5"><div className="h-full rounded-full bg-[#d7ef8d]" style={{width:`${Math.max(2,(row.sales/maxSales)*100)}%`}}/></div></div>)}</div></div><div className="rounded-3xl border border-white/10 bg-[#101c17] p-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#8fa49a]">Leaderboard</p><h2 className="mt-1 text-lg font-black">Top shopkeepers by sales</h2><div className="mt-5 space-y-3">{data.topShops.slice(0,8).map((shop,i)=><div key={shop.shopId} className="flex items-center gap-3 rounded-2xl bg-white/[.03] p-3"><div className="flex h-8 w-8 items-center justify-center rounded-xl bg-[#d7ef8d] text-xs font-black text-[#10251b]">{i+1}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{shop.shopName}</div><div className="text-[11px] text-[#8fa49a]">{shop.orders} orders • {shop.margin.toFixed(1)}% margin</div></div><div className="text-sm font-black">{money(shop.sales)}</div></div>)}{!data.topShops.length&&<p className="text-sm text-[#8fa49a]">Sales will appear here after delivered orders are recorded.</p>}</div></div></div><div className="grid gap-4 sm:grid-cols-3"><Stat label="Active shops" value={data.totals.shops}/><Stat label="Active staff" value={data.totals.staff}/><Stat label="Pending approvals" value={data.totals.pendingApplications}/></div></div>}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-[#101c17] p-4"><div className="text-xs text-[#8fa49a]">{label}</div><div className="mt-1 text-xl font-black">{value.toLocaleString('en-IN')}</div></div>}
